### ISSUE TITLE
Can't execute run-travis-ci.sh more than one time locally

### ISSUE THREAD

**Issue by rexim** [rexim/org-cliplink#31]
Have checked only on Linux.

Try to execute run-travis-ci.sh more than one time. On the second run see:

```
Starting testing server...
Serving /home/rexim/Programming/mine/org-cliplink/test-data/site directory
Starting HTTP Server...
Starting HTTPS Server...
Starting Gziped HTTP Server...
Starting Gziped HTTPS Server...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./run-testing-server.py", line 16, in start_http_server
    httpd = SocketServer.TCPServer(("", port), SimpleHTTPServer.SimpleHTTPRequestHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./run-testing-server.py", line 27, in start_gziped_http_server
    httpd = SocketServer.TCPServer(("", port), GzipSimpleHTTPServer.SimpleHTTPRequestHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```

Looks like something is not released after testing server being killed. Need to fix that.

**Comment by rexim** [comment]
This is strange... When I run `run-testing-server.py` and then just kill (by `kill` command or ^C) everything's ok.

**Comment by rexim** [comment]
```
➜  ~  sudo netstat -anp | grep 4444
tcp        0      0 127.0.0.1:4444          127.0.0.1:35223         TIME_WAIT   -               
➜  ~  
```

**Comment by rexim** [comment]
http://superuser.com/questions/173535/what-are-close-wait-and-time-wait-states

**Comment by rexim** [comment]
Looks like it happens due to using `SocketServer.TCPServer` instead of `SocketServer.TCPServer`
